# Generated by Django 3.2 on 2021-04-14 22:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='product code')),
                ('price', models.CharField(blank=True, max_length=10, null=True, verbose_name='product price')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='currency')),
                ('image', models.ImageField(blank=True, default=products.models.get_prduct_default_image_filepath, null=True, upload_to=products.models.get_product_image_filepath, verbose_name='image path')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Invalid quantity')], verbose_name='product quantity')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date-Time added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date-Time added')),
                ('qr_code', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
