# Generated by Django 3.2 on 2021-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_paid',
            field=models.BooleanField(default='False'),
        ),
    ]
